
----------------------------------------------------------------------------------------------------------------
-- CREATE ROLES
----------------------------------------------------------------------------------------------------------------
USE ROLE SECURITYADMIN;

----------------------------------------------------------------------------------------------------------------
----  CREATE FUNCTIONAL ROLES
----------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------
------  Domain Admin role for Domain
----------------------------------------------------------------------------------------------------------------
-------- None
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}} COMMENT = 'Domain Admin role for {{DOMAIN_NAME}} Data domain.';


----------------------------------------------------------------------------------------------------------------
------  ETL role for Domain
----------------------------------------------------------------------------------------------------------------
-------- DEV
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} COMMENT = 'Functional ETL role on DEV environment for {{DOMAIN_NAME}} Data domain.';
-------- TEST
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} COMMENT = 'Functional ETL role on TEST environment for {{DOMAIN_NAME}} Data domain.';
-------- PROD
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} COMMENT = 'Functional ETL role on PROD environment for {{DOMAIN_NAME}} Data domain.';

----------------------------------------------------------------------------------------------------------------
------  BI role for Domain
----------------------------------------------------------------------------------------------------------------
-------- DEV
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} COMMENT = 'Functional BI role on DEV environment for {{DOMAIN_NAME}} Data domain.';
-------- TEST
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} COMMENT = 'Functional BI role on TEST environment for {{DOMAIN_NAME}} Data domain.';
-------- PROD
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} COMMENT = 'Functional BI role on PROD environment for {{DOMAIN_NAME}} Data domain.';

----------------------------------------------------------------------------------------------------------------
------  {{DEVELOPER_ROLE}} role for Domain
----------------------------------------------------------------------------------------------------------------
-------- {{NON-PROD}}
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{DEVELOPER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} COMMENT = 'Functional {{DEVELOPER_ROLE}} role on {{NON-PROD}} environment for {{DOMAIN_NAME}} Data domain.';

----------------------------------------------------------------------------------------------------------------
------  {{OPERATOR_ROLE}} role for Domain
----------------------------------------------------------------------------------------------------------------
-------- PROD
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{OPERATOR_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} COMMENT = 'Functional {{OPERATOR_ROLE}} role on PROD environment for {{DOMAIN_NAME}} Data domain.';

----------------------------------------------------------------------------------------------------------------
------  {{READER_ROLE}} role for Domain
----------------------------------------------------------------------------------------------------------------
-------- {{NON-PROD}}
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} COMMENT = 'Functional {{READER_ROLE}} role on {{NON-PROD}} environment for {{DOMAIN_NAME}} Data domain.';
-------- PROD
CREATE ROLE {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} COMMENT = 'Functional {{READER_ROLE}} role on PROD environment for {{DOMAIN_NAME}} Data domain.';

----------------------------------------------------------------------------------------------------------------
----  CREATE ACCESS ROLES
----------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------
------  Object Level role for Domain
----------------------------------------------------------------------------------------------------------------
-------- DEV
CREATE ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} COMMENT = 'Access role with Object Level privileges on DEV environment for {{DOMAIN_NAME}} Data domain.';
-------- TEST
CREATE ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} COMMENT = 'Access role with Object Level privileges on TEST environment for {{DOMAIN_NAME}} Data domain.';
-------- PROD
CREATE ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} COMMENT = 'Access role with Object Level privileges on PROD environment for {{DOMAIN_NAME}} Data domain.';

----------------------------------------------------------------------------------------------------------------
------  Read Only role for Domain
----------------------------------------------------------------------------------------------------------------
-------- DEV
CREATE ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} COMMENT = 'Access role with Read Only privileges on DEV environment for {{DOMAIN_NAME}} Data domain.';
-------- TEST
CREATE ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} COMMENT = 'Access role with Read Only privileges on TEST environment for {{DOMAIN_NAME}} Data domain.';
-------- PROD
CREATE ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} COMMENT = 'Access role with Read Only privileges on PROD environment for {{DOMAIN_NAME}} Data domain.';

----------------------------------------------------------------------------------------------------------------
------  Read Write role for Domain
----------------------------------------------------------------------------------------------------------------
-------- DEV
CREATE ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} COMMENT = 'Access role with Read-Write privileges on DEV environment for {{DOMAIN_NAME}} Data domain.';
-------- TEST
CREATE ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} COMMENT = 'Access role with Read-Write privileges on TEST environment for {{DOMAIN_NAME}} Data domain.';
-------- PROD
CREATE ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} COMMENT = 'Access role with Read-Write privileges on PROD environment for {{DOMAIN_NAME}} Data domain.';


----------------------------------------------------------------------------------------------------------------
----  Grant OWNERSHIP required by SSO
----------------------------------------------------------------------------------------------------------------
USE ROLE SECURITYADMIN;

GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}} TO ROLE AAD_PROVISIONER WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{DEVELOPER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} TO ROLE AAD_PROVISIONER WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{OPERATOR_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE AAD_PROVISIONER WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} TO ROLE AAD_PROVISIONER WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE AAD_PROVISIONER WITH GRANT OPTION COPY CURRENT GRANTS;


----------------------------------------------------------------------------------------------------------------
----  Grant default OWNERSHIP
----------------------------------------------------------------------------------------------------------------
USE ROLE SECURITYADMIN;

GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_DEV}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_TEST}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_PROD}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SECURITYADMIN WITH GRANT OPTION COPY CURRENT GRANTS;


----------------------------------------------------------------------------------------------------------------
----  Grant default USAGE on roles
----------------------------------------------------------------------------------------------------------------
USE ROLE SECURITYADMIN;

GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_DEV}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_TEST}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_PROD}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{DEVELOPER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{OPERATOR_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE SYSADMIN ;
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE SYSADMIN ;

----------------------------------------------------------------------------------------------------------------
----  GRANT Access Roles to Roles
----------------------------------------------------------------------------------------------------------------
USE ROLE SECURITYADMIN;

----------------------------------------------------------------------------------------------------------------
------  Grant Access Role Object Level
----------------------------------------------------------------------------------------------------------------
-------- DEV
GRANT ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DEVELOPER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}};
-------- TEST
GRANT ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DEVELOPER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}};
-------- PROD
GRANT ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{OPERATOR_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};

----------------------------------------------------------------------------------------------------------------
------  Grant Access Role Read Only
----------------------------------------------------------------------------------------------------------------
-------- DEV
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_DEV}};
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}};
-------- TEST
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_TEST}};
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}};
-------- PROD
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_PROD}};
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};

----------------------------------------------------------------------------------------------------------------
------  Grant Access Role Read Write
----------------------------------------------------------------------------------------------------------------
-------- DEV
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DEVELOPER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}};
-------- TEST
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DEVELOPER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}};
-------- PROD
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{OPERATOR_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};


----------------------------------------------------------------------------------------------------------------
-- CREATE DATABASES, SCHEMAS AND DEFINE OWNERSHIP
----------------------------------------------------------------------------------------------------------------
USE ROLE SYSADMIN;

----------------------------------------------------------------------------------------------------------------
---- Create objects for DEV environment
----------------------------------------------------------------------------------------------------------------

---- {{DOMAIN_NAME}}_DEV
------ Create objects
CREATE DATABASE {{DOMAIN_NAME}}_DEV COMMENT = 'Database of {{DOMAIN_NAME}} Data Data Domain on Development environment';
CREATE SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} WITH MANAGED ACCESS COMMENT = '{{CORE_SCHEMA}} schema in {{DOMAIN_NAME}} Data database on DEV environment';
CREATE SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} WITH MANAGED ACCESS COMMENT = 'Reporting/Final schema in {{DOMAIN_NAME}} Data database on DEV environment';
CREATE SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} WITH MANAGED ACCESS COMMENT = 'Staging schema in {{DOMAIN_NAME}} Data database on DEV environment';

GRANT OWNERSHIP ON SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};
GRANT OWNERSHIP ON SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};
GRANT OWNERSHIP ON SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};
GRANT OWNERSHIP ON DATABASE {{DOMAIN_NAME}}_DEV TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};

----------------------------------------------------------------------------------------------------------------
---- Create objects for PROD environment
----------------------------------------------------------------------------------------------------------------

---- {{DOMAIN_NAME}}_PROD
------ Create objects
CREATE DATABASE {{DOMAIN_NAME}}_PROD COMMENT = 'Database of {{DOMAIN_NAME}} Data Data Domain on Production environment';
CREATE SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} WITH MANAGED ACCESS COMMENT = '{{CORE_SCHEMA}} schema in {{DOMAIN_NAME}} Data database on PROD environment';
CREATE SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} WITH MANAGED ACCESS COMMENT = 'Reporting/Final schema in {{DOMAIN_NAME}} Data database on PROD environment';
CREATE SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} WITH MANAGED ACCESS COMMENT = 'Staging schema in {{DOMAIN_NAME}} Data database on PROD environment';
------ Grant Ownership
GRANT OWNERSHIP ON SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};
GRANT OWNERSHIP ON SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};
GRANT OWNERSHIP ON SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};
GRANT OWNERSHIP ON DATABASE {{DOMAIN_NAME}}_PROD TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};

----------------------------------------------------------------------------------------------------------------
---- Create objects for TEST environment
----------------------------------------------------------------------------------------------------------------

---- {{DOMAIN_NAME}}_TEST
------ Create objects
CREATE DATABASE {{DOMAIN_NAME}}_TEST COMMENT = 'Database of {{DOMAIN_NAME}} Data Data Domain on Test / UAT environment';
CREATE SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} WITH MANAGED ACCESS COMMENT = '{{CORE_SCHEMA}} schema in {{DOMAIN_NAME}} Data database on TEST environment';
CREATE SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} WITH MANAGED ACCESS COMMENT = 'Reporting/Final schema in {{DOMAIN_NAME}} Data database on TEST environment';
CREATE SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} WITH MANAGED ACCESS COMMENT = 'Staging schema in {{DOMAIN_NAME}} Data database on TEST environment';
------ Grant Ownership
GRANT OWNERSHIP ON SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};
GRANT OWNERSHIP ON SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};
GRANT OWNERSHIP ON SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};
GRANT OWNERSHIP ON DATABASE {{DOMAIN_NAME}}_TEST TO ROLE {{ACCOUNT_NAME}}_SNFK_{{DOMAIN_ADMIN}}_{{DOMAIN_NAME}};


----------------------------------------------------------------------------------------------------------------
-- CREATE WAREHOUSES
----------------------------------------------------------------------------------------------------------------
USE ROLE SYSADMIN;

---- Create warehouses for users of role BI
------ {{NON-PROD}}
CREATE WAREHOUSE WH_{{ACCOUNT}}_XS_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = True MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';
GRANT USAGE          ON WAREHOUSE WH_{{ACCOUNT}}_XS_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} TO {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_DEV}};
GRANT USAGE          ON WAREHOUSE WH_{{ACCOUNT}}_XS_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} TO {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_TEST}};

------ PROD
CREATE WAREHOUSE WH_{{ACCOUNT}}_XS_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = True MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';
GRANT USAGE          ON WAREHOUSE WH_{{ACCOUNT}}_XS_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_PROD}};

---- Create warehouses for users of role {{DEVELOPER_ROLE}}
------ {{NON-PROD}}
CREATE WAREHOUSE WH_{{ACCOUNT}}_XS_DEVELOPMENT_{{DOMAIN_NAME}}_{{NON-PROD}} WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = True MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';
GRANT USAGE, MONITOR ON WAREHOUSE WH_{{ACCOUNT}}_XS_DEVELOPMENT_{{DOMAIN_NAME}}_{{NON-PROD}} TO {{ACCOUNT_NAME}}_SNFK_{{DEVELOPER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}};

---- Create warehouses for users of role {{OPERATOR_ROLE}}
------ PROD
CREATE WAREHOUSE WH_{{ACCOUNT}}_XS_OPERATIONS_{{DOMAIN_NAME}}_PROD WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = True MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';
GRANT USAGE, MONITOR ON WAREHOUSE WH_{{ACCOUNT}}_XS_OPERATIONS_{{DOMAIN_NAME}}_PROD TO {{ACCOUNT_NAME}}_SNFK_{{OPERATOR_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};

---- Create warehouses for users of role ETL
------ {{NON-PROD}}
CREATE WAREHOUSE WH_{{ACCOUNT}}_XS_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = True MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';
GRANT USAGE          ON WAREHOUSE WH_{{ACCOUNT}}_XS_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} TO {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE          ON WAREHOUSE WH_{{ACCOUNT}}_XS_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}} TO {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};

------ PROD
CREATE WAREHOUSE WH_{{ACCOUNT}}_XS_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = True MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';
GRANT USAGE          ON WAREHOUSE WH_{{ACCOUNT}}_XS_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};


---- Create warehouses for users of role {{READER_ROLE}}
------ {{NON-PROD}}
CREATE WAREHOUSE WH_{{ACCOUNT}}_XS_{{READER_ROLE}}S_{{DOMAIN_NAME}}_{{NON-PROD}} WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = True MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';
GRANT USAGE, MONITOR ON WAREHOUSE WH_{{ACCOUNT}}_XS_{{READER_ROLE}}S_{{DOMAIN_NAME}}_{{NON-PROD}} TO {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}};

------ PROD
CREATE WAREHOUSE WH_{{ACCOUNT}}_XS_{{READER_ROLE}}S_{{DOMAIN_NAME}}_{{PROD}} WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = True MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';
GRANT USAGE, MONITOR ON WAREHOUSE WH_{{ACCOUNT}}_XS_{{READER_ROLE}}S_{{DOMAIN_NAME}}_{{PROD}} TO {{ACCOUNT_NAME}}_SNFK_{{READER_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};



----------------------------------------------------------------------------------------------------------------
-- GRANT PRIVILEGES TO ACCESS ROLES
----------------------------------------------------------------------------------------------------------------
USE ROLE SECURITYADMIN;

----------------------------------------------------------------------------------------------------------------
---- Grant for OL Access roles
----------------------------------------------------------------------------------------------------------------
------ DEV
-------- {{DOMAIN_NAME}}_DEV
GRANT USAGE ON DATABASE {{DOMAIN_NAME}}_DEV TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE,
      ADD SEARCH OPTIMIZATION,
      CREATE AGGREGATION POLICY,
      CREATE ALERT,
      CREATE DATASET,
      CREATE DYNAMIC TABLE,
      CREATE EXTERNAL TABLE,
      CREATE FILE FORMAT,
      CREATE FUNCTION,
      CREATE GIT REPOSITORY,
      CREATE ICEBERG TABLE,
      CREATE MATERIALIZED VIEW,
      CREATE PIPE,
      CREATE PROCEDURE,
      CREATE PROJECTION POLICY,
      CREATE SECRET,
      CREATE SEQUENCE,
      CREATE {{STAGE_SCHEMA}},
      CREATE STREAM,
      CREATE TABLE,
      CREATE TAG,
      CREATE TASK,
      CREATE TEMPORARY TABLE,
      CREATE VIEW,
      MONITOR                   ON SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE,
      ADD SEARCH OPTIMIZATION,
      CREATE AGGREGATION POLICY,
      CREATE ALERT,
      CREATE DATASET,
      CREATE DYNAMIC TABLE,
      CREATE EXTERNAL TABLE,
      CREATE FILE FORMAT,
      CREATE FUNCTION,
      CREATE GIT REPOSITORY,
      CREATE ICEBERG TABLE,
      CREATE MATERIALIZED VIEW,
      CREATE PIPE,
      CREATE PROCEDURE,
      CREATE PROJECTION POLICY,
      CREATE SECRET,
      CREATE SEQUENCE,
      CREATE {{STAGE_SCHEMA}},
      CREATE STREAM,
      CREATE TABLE,
      CREATE TAG,
      CREATE TASK,
      CREATE TEMPORARY TABLE,
      CREATE VIEW,
      MONITOR                   ON SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE,
      ADD SEARCH OPTIMIZATION,
      CREATE AGGREGATION POLICY,
      CREATE ALERT,
      CREATE DATASET,
      CREATE DYNAMIC TABLE,
      CREATE EXTERNAL TABLE,
      CREATE FILE FORMAT,
      CREATE FUNCTION,
      CREATE GIT REPOSITORY,
      CREATE ICEBERG TABLE,
      CREATE MATERIALIZED VIEW,
      CREATE PIPE,
      CREATE PROCEDURE,
      CREATE PROJECTION POLICY,
      CREATE SECRET,
      CREATE SEQUENCE,
      CREATE {{STAGE_SCHEMA}},
      CREATE STREAM,
      CREATE TABLE,
      CREATE TAG,
      CREATE TASK,
      CREATE TEMPORARY TABLE,
      CREATE VIEW,
      MONITOR                   ON SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};

GRANT ALL ON FUTURE TABLES       IN SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT ALL ON FUTURE VIEWS        IN SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT ALL ON FUTURE TABLES       IN SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT ALL ON FUTURE VIEWS        IN SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT ALL ON FUTURE TABLES       IN SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT ALL ON FUTURE VIEWS        IN SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};


------ PROD
-------- {{DOMAIN_NAME}}_PROD
GRANT USAGE ON DATABASE {{DOMAIN_NAME}}_PROD TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT USAGE,
      ADD SEARCH OPTIMIZATION,
      CREATE AGGREGATION POLICY,
      CREATE ALERT,
      CREATE DATASET,
      CREATE DYNAMIC TABLE,
      CREATE EXTERNAL TABLE,
      CREATE FILE FORMAT,
      CREATE FUNCTION,
      CREATE GIT REPOSITORY,
      CREATE ICEBERG TABLE,
      CREATE MATERIALIZED VIEW,
      CREATE PIPE,
      CREATE PROCEDURE,
      CREATE PROJECTION POLICY,
      CREATE SECRET,
      CREATE SEQUENCE,
      CREATE {{STAGE_SCHEMA}},
      CREATE STREAM,
      CREATE TABLE,
      CREATE TAG,
      CREATE TASK,
      CREATE TEMPORARY TABLE,
      CREATE VIEW,
      MONITOR                  ON SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT USAGE,
      ADD SEARCH OPTIMIZATION,
      CREATE AGGREGATION POLICY,
      CREATE ALERT,
      CREATE DATASET,
      CREATE DYNAMIC TABLE,
      CREATE EXTERNAL TABLE,
      CREATE FILE FORMAT,
      CREATE FUNCTION,
      CREATE GIT REPOSITORY,
      CREATE ICEBERG TABLE,
      CREATE MATERIALIZED VIEW,
      CREATE PIPE,
      CREATE PROCEDURE,
      CREATE PROJECTION POLICY,
      CREATE SECRET,
      CREATE SEQUENCE,
      CREATE {{STAGE_SCHEMA}},
      CREATE STREAM,
      CREATE TABLE,
      CREATE TAG,
      CREATE TASK,
      CREATE TEMPORARY TABLE,
      CREATE VIEW,
      MONITOR                   ON SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT USAGE,
      ADD SEARCH OPTIMIZATION,
      CREATE AGGREGATION POLICY,
      CREATE ALERT,
      CREATE DATASET,
      CREATE DYNAMIC TABLE,
      CREATE EXTERNAL TABLE,
      CREATE FILE FORMAT,
      CREATE FUNCTION,
      CREATE GIT REPOSITORY,
      CREATE ICEBERG TABLE,
      CREATE MATERIALIZED VIEW,
      CREATE PIPE,
      CREATE PROCEDURE,
      CREATE PROJECTION POLICY,
      CREATE SECRET,
      CREATE SEQUENCE,
      CREATE {{STAGE_SCHEMA}},
      CREATE STREAM,
      CREATE TABLE,
      CREATE TAG,
      CREATE TASK,
      CREATE TEMPORARY TABLE,
      CREATE VIEW,
      MONITOR                   ON SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};

GRANT ALL ON FUTURE TABLES      IN SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT ALL ON FUTURE VIEWS		IN SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT ALL ON FUTURE TABLES      IN SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT ALL ON FUTURE VIEWS       IN SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT ALL ON FUTURE TABLES      IN SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT ALL ON FUTURE VIEWS       IN SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};


------ TEST
-------- {{DOMAIN_NAME}}_TEST
GRANT USAGE ON DATABASE {{DOMAIN_NAME}}_TEST TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT USAGE,
      ADD SEARCH OPTIMIZATION,
      CREATE AGGREGATION POLICY,
      CREATE ALERT,
      CREATE DATASET,
      CREATE DYNAMIC TABLE,
      CREATE EXTERNAL TABLE,
      CREATE FILE FORMAT,
      CREATE FUNCTION,
      CREATE GIT REPOSITORY,
      CREATE ICEBERG TABLE,
      CREATE MATERIALIZED VIEW,
      CREATE PIPE,
      CREATE PROCEDURE,
      CREATE PROJECTION POLICY,
      CREATE SECRET,
      CREATE SEQUENCE,
      CREATE {{STAGE_SCHEMA}},
      CREATE STREAM,
      CREATE TABLE,
      CREATE TAG,
      CREATE TASK,
      CREATE TEMPORARY TABLE,
      CREATE VIEW,
      MONITOR                  ON SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT USAGE,
      ADD SEARCH OPTIMIZATION,
      CREATE AGGREGATION POLICY,
      CREATE ALERT,
      CREATE DATASET,
      CREATE DYNAMIC TABLE,
      CREATE EXTERNAL TABLE,
      CREATE FILE FORMAT,
      CREATE FUNCTION,
      CREATE GIT REPOSITORY,
      CREATE ICEBERG TABLE,
      CREATE MATERIALIZED VIEW,
      CREATE PIPE,
      CREATE PROCEDURE,
      CREATE PROJECTION POLICY,
      CREATE SECRET,
      CREATE SEQUENCE,
      CREATE {{STAGE_SCHEMA}},
      CREATE STREAM,
      CREATE TABLE,
      CREATE TAG,
      CREATE TASK,
      CREATE TEMPORARY TABLE,
      CREATE VIEW,
      MONITOR                   ON SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT USAGE,
      ADD SEARCH OPTIMIZATION,
      CREATE AGGREGATION POLICY,
      CREATE ALERT,
      CREATE DATASET,
      CREATE DYNAMIC TABLE,
      CREATE EXTERNAL TABLE,
      CREATE FILE FORMAT,
      CREATE FUNCTION,
      CREATE GIT REPOSITORY,
      CREATE ICEBERG TABLE,
      CREATE MATERIALIZED VIEW,
      CREATE PIPE,
      CREATE PROCEDURE,
      CREATE PROJECTION POLICY,
      CREATE SECRET,
      CREATE SEQUENCE,
      CREATE {{STAGE_SCHEMA}},
      CREATE STREAM,
      CREATE TABLE,
      CREATE TAG,
      CREATE TASK,
      CREATE TEMPORARY TABLE,
      CREATE VIEW,
      MONITOR                   ON SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};

GRANT ALL ON FUTURE TABLES       IN SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT ALL ON FUTURE VIEWS        IN SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT ALL ON FUTURE TABLES       IN SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT ALL ON FUTURE VIEWS        IN SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT ALL ON FUTURE TABLES       IN SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT ALL ON FUTURE VIEWS        IN SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{OBJECT_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};


----------------------------------------------------------------------------------------------------------------
---- Grant for RO Access roles
----------------------------------------------------------------------------------------------------------------
------ DEV
-------- {{DOMAIN_NAME}}_DEV
GRANT USAGE ON DATABASE {{DOMAIN_NAME}}_DEV TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};

GRANT SELECT                      ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT                      ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT                      ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};



------ PROD
-------- {{DOMAIN_NAME}}_PROD
GRANT USAGE ON DATABASE {{DOMAIN_NAME}}_PROD TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};

GRANT SELECT                      ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT                      ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT                      ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};



------ TEST
-------- {{DOMAIN_NAME}}_TEST
GRANT USAGE ON DATABASE {{DOMAIN_NAME}}_TEST TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};

GRANT SELECT                      ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT                      ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT                      ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};



----------------------------------------------------------------------------------------------------------------
---- Grant for RW Access roles
----------------------------------------------------------------------------------------------------------------
------ DEV
-------- {{DOMAIN_NAME}}_DEV
GRANT USAGE ON DATABASE {{DOMAIN_NAME}}_DEV TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};

GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_DEV.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_DEV.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_DEV.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}};



------ PROD
-------- {{DOMAIN_NAME}}_PROD
GRANT USAGE ON DATABASE {{DOMAIN_NAME}}_PROD TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};

GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_PROD.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_PROD.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_PROD.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}};



------ TEST
-------- {{DOMAIN_NAME}}_TEST
GRANT USAGE ON DATABASE {{DOMAIN_NAME}}_TEST TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT USAGE                       ON SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};

GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_TEST.{{CORE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_TEST.{{RPT_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};
GRANT SELECT                      ON FUTURE VIEWS  IN SCHEMA {{DOMAIN_NAME}}_TEST.{{STAGE_SCHEMA}} TO ROLE {{ACCOUNT_NAME}}_{{READ_WRITE_ONLY_LEVEL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}};





----------------------------------------------------------------------------------------------------------------
-- CREATE SERVICE USERS ASD SET ROLES
----------------------------------------------------------------------------------------------------------------
USE ROLE SECURITYADMIN;

----------------------------------------------------------------------------------------------------------------
---- Create service account users
----------------------------------------------------------------------------------------------------------------
------ Create BI service account user
------ DEV
CREATE USER SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{DEV}}   
	LOGIN_NAME = SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{DEV}}   
	DISPLAY_NAME = SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{DEV}}  ;
------ PROD
CREATE USER SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{PROD}}  
	LOGIN_NAME = SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{PROD}}  
	DISPLAY_NAME = SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} ;
------ TEST
CREATE USER SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{TEST}}  
	LOGIN_NAME = SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{TEST}}  
	DISPLAY_NAME = SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} ;
	
------ Create ETL service account user
------ DEV
CREATE USER SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{DEV}} 
	LOGIN_NAME = SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{DEV}} 
	DISPLAY_NAME = SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{DEV}};
------ PROD
CREATE USER SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{PROD}} 
	LOGIN_NAME = SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{PROD}} 
	DISPLAY_NAME = SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{PROD}};
------ TEST
CREATE USER SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{TEST}} 
	LOGIN_NAME = SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{TEST}} 
	DISPLAY_NAME = SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{TEST}};


------ DEV
ALTER  USER SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{DEV}}   
	    SET DEFAULT_ROLE = '{{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_DEV}}', 
	        DEFAULT_NAMESPACE = '{{DOMAIN_NAME}}_DEV', 
		    DEFAULT_WAREHOUSE = 'WH_{{ACCOUNT}}_XS_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}}';
------ PROD
ALTER  USER SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{PROD}}  
		SET DEFAULT_ROLE = '{{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_PROD}}', 
			DEFAULT_NAMESPACE = '{{DOMAIN_NAME}}_PROD', 
			DEFAULT_WAREHOUSE = 'WH_{{ACCOUNT}}_XS_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{PROD}}';
------ TEST
ALTER  USER SVC_{{ACCOUNT}}_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{TEST}}  
		SET DEFAULT_ROLE = '{{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_TEST}}', 
			DEFAULT_NAMESPACE = '{{DOMAIN_NAME}}_TEST', 
			DEFAULT_WAREHOUSE = 'WH_{{ACCOUNT}}_XS_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}}';

------ DEV
ALTER  USER SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{DEV}} 
		SET DEFAULT_ROLE = '{{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}}', 
			DEFAULT_NAMESPACE = '{{DOMAIN_NAME}}_DEV', 
			DEFAULT_WAREHOUSE = 'WH_{{ACCOUNT}}_XS_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}}';
------ PROD
ALTER  USER SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{PROD}} 
		SET DEFAULT_ROLE = '{{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}}', 
			DEFAULT_NAMESPACE = '{{DOMAIN_NAME}}_PROD', 
			DEFAULT_WAREHOUSE = 'WH_{{ACCOUNT}}_XS_{{ETL_ROLE}}_{{DOMAIN_NAME}}_PROD';
------ TEST
ALTER  USER SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{TEST}} 
		SET DEFAULT_ROLE = '{{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}}', 
			DEFAULT_NAMESPACE = '{{DOMAIN_NAME}}_TEST', 
			DEFAULT_WAREHOUSE = 'WH_{{ACCOUNT}}_XS_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{NON-PROD}}';

----------------------------------------------------------------------------------------------------------------
---- Grant roles service account users
----------------------------------------------------------------------------------------------------------------
------ Grant roles to BI service account user
------ DEV
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_DEV}}   TO USER SVC_{{ACCOUNT}}_BI_{{DOMAIN_NAME}}_DEV;
------ PROD
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_PROD}}  TO USER SVC_{{ACCOUNT}}_BI_{{DOMAIN_NAME}}_PROD;
------ TEST
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{BI_ROLE}}_{{DOMAIN_NAME}}_{{ENV_TEST}}  TO USER SVC_{{ACCOUNT}}_BI_{{DOMAIN_NAME}}_TEST;

------ Grant roles to ETL service account user
------ DEV
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{DEV}}  TO USER SVC_{{ACCOUNT}}_DBT_{{DOMAIN_NAME}}_DEV;
------ PROD
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{PROD}} TO USER SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{PROD}};
------ TEST
GRANT ROLE {{ACCOUNT_NAME}}_SNFK_{{ETL_ROLE}}_{{DOMAIN_NAME}}_{{TEST}} TO USER SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{TEST}};

ALTER USER "SVC_{{ACCOUNT}}_DBT_{{DOMAIN_NAME}}_DEV" SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAptoC1jaKFaKgjiRbCaIi
ZbJj6hzBl9HvNGZcQF5ekB/yh8FrtrWrt+z/D5CcJG+QlZuhkvrG8/bXoKA3ZHkZ
OKnD/hklzKvR0Kwkti/3QXae2hvKjKygY+EGi8W9w0nsesCjGvRt6ErmB/6lHtzc
MBTT05N4MHWGLcuSbns8zr/1bYK38kujyB9QF50qpKre1Esh5Y4WHblVP8Rc57NC
3GQkbzDsi9nnbm6AJEJxsnkmILnrGS9DZdly0HPmsDFjAYg+Q8+Z9w10bpzqpyQ3
viFWXJQeLTSxLEBDyer/JYy+8xbBMDLM6gYCC4wJYdRWyicsRVkNbC5AeihskaOR
bQIDAQAB';

ALTER USER "SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{PROD}}" SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmN+s9DZgVrcz258gqSY5
CJoYs76CVvdl6NTpvHRISn207dYfVk7o8UT0ihdpp9VMnc7E/c1KgoHsxa51kJQP
hoI5e2Ced8Wd8oHK5GQyf/5Qai67iweHpS8exLiWP6BoxZJFEiq1EHqH91T7rVYQ
/93aqLPvVTnNJ0yBD+BOFK9ZsBQA3HYIx7ec5uOf/ERj1vtCA89a42psJIK2ukEH
8l+43mLd7byQnOfxdG7OEwyfGfkOrHuRT87Zah94OjLbbhB0NKCE+MR+U/iTWaDT
s0fltLfdtWACJm22CnjBOjo1D54rSxjl/VqmjS5ztdVrcvRDCaUaqPblL29ZBI4k
AQIDAQAB';

ALTER USER "SVC_{{ACCOUNT}}_{{DBT_USER}}_{{DOMAIN_NAME}}_{{TEST}}" SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4GaWfKux5uD/HMihOJOA
KgYpz40o5Wv4FDoRpnJ5oYBEBda3/eGxHsJEBVXcB2NrkLzDvPf4iwGhCabm2CJC
7bcsAsmKREkO+w+CXJNUjHfxshMOV7raX7+e8TaqqfYh8lcx211UObCNx0FnKzBE
9G1iZPse0lpNawiR7GtHdxMX/oub3Jne68H9NSSQAQLslNImo5LKRJGos744Jwga
bvuJn/tFGkn9V3gGzeir5cQLwXMMeNzLqEhyLmMNmwL6dOLi/2z81q1yzuxnbqK6
BTzRNOEjWofpkudT2tbj5TqKWL7Z96jengDqbqp15eIOLBGEkTYpHShH5IIzbQoY
BQIDAQAB';






